language: python
sudo: false
services:
  - mongodb

cache:
  directories:
    - $HOME/.pip-cache/

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.3"
      env: TOXENV=py33 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.4"
      env: TOXENV=py34 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.5"
      env: TOXENV=py35 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "pypy"
      env: TOXENV=pypy PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "2.7"
      env: TOXENV=docs PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "2.7"
      env: TOXENV=acceptance PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.5"
      env: TOXENV=acceptance3 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache

script:
  - ./testscript.sh

after_success:
  - ./after_success.sh -F $TOXENV

notifications:
  email:
    on_success: always
    on_failure: always
  pushover:
    users:
    - secure: "huDUVxK/+QQJ7Fysln0go7N+Hl+DSkgdeWJMME+b4UHvpbIWD2Ac4Z2kKv5o1NFqcWX+bhBp9gLydmbpK6nkbQwtxtXRBvE/rR/j9rfgCmh1tMH3zIg3fL4I9dWDBWyWJjAIb7xHVR9OSqJ+GeHKXlw1Lc6UoYEbmLnTOznofM8="
    api_key:
      secure: "IzTUdTw929bdSNtkD1lCFVQJzw4lNKXinEox95InTClp242zAY8j3cSsodlweu1sfPog4SRzkSzC/2KrMh4I9EyqBLlFSJDwFr4+BhK726sZu2U+eZRXlALtJ2UNX1cwKQo9kw9TwktPlyokt1CBJePWgfCOOiik0wo7EhacgRI="
branches:
  except:
    - "/^noci-.*$/"
